# -*- coding: utf-8 -*-
"""Especificaciones de los 18 retos de RootPath (3 por categoría, dificultad 1/2/3).

Narrativa dominicana: expedientes de investigación ficticios.
Regla UCE: solo ambientación (campus, vida estudiantil), nunca sistemas reales.
"""

# Dificultad -> puntos
POINTS = {1: 50, 2: 100, 3: 200}
DIFF_NAME = {1: "Fácil", 2: "Media", 3: "Difícil"}

SPECS = [
    # ============================= WEB =============================
    dict(
        slug="el-colmadon-de-la-duarte", title="El Colmadón de la Duarte",
        category="Web", difficulty=1,
        template="web_comment",
        cert="Fundamentos de Pentesting (eJPT)", domain="Reconocimiento y Web",
        series="casos-rd", region="Gran Santo Domingo",
        rd="RD-031", provincia="Distrito Nacional",
        ubicacion="Colmado 'La Esquina del Coro', Av. Duarte esq. Calle París",
        fecha="2026-08-14", incidente="Filtración de información en portal web de un colmado en línea",
        resumen="El colmado 'La Esquina del Coro' lanzó su tienda en línea para vender víveres y recargas. Una denuncia anónima indica que el desarrollador dejó información sensible en el propio código de la página. Hay que revisar lo que no se ve a simple vista.",
        evidencias=["Portal web de la tienda en línea", "Código fuente accesible desde el navegador"],
        objetivo_tecnico="Inspeccionar el código fuente HTML de la página y localizar información oculta en un comentario.",
        objetivo_investigacion="Determinar qué dato confidencial quedó expuesto por una mala práctica de desarrollo.",
        hint1="Lo que el navegador muestra no es todo lo que existe. Revisa el código fuente (Ctrl+U o clic derecho > Ver código fuente).",
        hint2="Busca comentarios HTML: las etiquetas <!-- ... --> suelen esconder notas de desarrolladores.",
        hint3="En uno de los comentarios del footer o del <head> hay una credencial o nota con el formato RP{...}.",
        spec=dict(port=80),
    ),
    dict(
        slug="el-parqueo-del-boulevard", title="El Parqueo del Boulevard",
        category="Web", difficulty=2,
        template="web_idor",
        cert="Fundamentos de Pentesting (eJPT)", domain="Reconocimiento y Web",
        series="casos-rd", region="Este",
        rd="RD-032", provincia="La Altagracia",
        ubicacion="Parqueo 'Boulevard del Este', Higüey",
        fecha="2026-08-19", incidente="Acceso no autorizado a tickets de estacionamiento de otros clientes",
        resumen="El parqueo digitalizó sus tickets: cada boleta se consulta por un número en la URL. Un cliente reportó que podía ver el ticket de otra persona. El sistema no valida que el ticket pertenezca a quien lo consulta.",
        evidencias=["Portal de consulta de tickets", "URLs con identificadores numéricos predecibles"],
        objetivo_tecnico="Explotar una referencia directa a objetos insegura (IDOR) para acceder a un ticket que no corresponde al usuario.",
        objetivo_investigacion="Recuperar el dato confidencial del ticket administrativo (ID 0 o un ID no listado).",
        hint1="Fíjate en el identificador que viaja en la URL (/ticket/<id>). ¿Qué pasa si cambias el número?",
        hint2="Los IDs empiezan en 1 para el público, pero suele existir un registro interno (prueba con 0).",
        hint3="Solicita /ticket/0 o recorre IDs pequeños hasta encontrar el ticket 'administrativo' con la nota interna.",
        spec=dict(port=80),
    ),
    dict(
        slug="la-banca-del-malecon", title="La Banca del Malecón",
        category="Web", difficulty=3,
        template="web_sqli",
        cert="Pentesting Intermedio (PNPT)", domain="Explotacion Web Avanzada",
        series="casos-rd", region="Nacional",
        rd="RD-033", provincia="Distrito Nacional",
        ubicacion="Portal de banca en línea 'Banca del Malecón' (entidad ficticia)",
        fecha="2026-08-27", incidente="Inyección SQL en el formulario de acceso a la banca en línea",
        resumen="Una entidad financiera ficticia expuso su portal de banca en línea. El formulario de login concatena directamente lo que escribe el usuario en la consulta SQL, sin sanitizar. Un investigador debe demostrar el fallo accediendo sin credenciales válidas.",
        evidencias=["Formulario de acceso (usuario/clave)", "Errores SQL visibles al probar comillas"],
        objetivo_tecnico="Realizar un bypass de autenticación mediante inyección SQL en el campo de usuario.",
        objetivo_investigacion="Acceder al panel como administrador y obtener la bandera que se muestra tras el acceso.",
        hint1="Prueba a escribir una comilla simple (') en el usuario y observa si aparece un error SQL.",
        hint2="La consulta es del tipo SELECT * FROM usuarios WHERE user='...' AND pass='...'. Cierra la comilla del usuario.",
        hint3="Usa una tautología: admin' OR '1'='1' -- y deja la clave vacía para saltarte la verificación.",
        spec=dict(port=80),
    ),

    # ============================ LINUX ============================
    dict(
        slug="el-servidor-de-la-cafeteria", title="El Servidor de la Cafetería",
        category="Linux", difficulty=1,
        template="linux_suid",
        cert="Fundamentos de Pentesting (eJPT)", domain="Explotacion de Sistemas Linux",
        series="casos-rd", region="Este",
        rd="RD-034", provincia="La Romana",
        ubicacion="Servidor del punto de venta de la cafetería del campus UCE",
        fecha="2026-09-02", incidente="Escalada de privilegios por binario SUID mal configurado",
        resumen="La cafetería del campus usa un servidor Linux para su punto de venta. El administrador dejó un binario con el bit SUID activado que permite leer archivos como root. Hay que escalar privilegios y leer la bandera protegida.",
        evidencias=["Acceso SSH con usuario 'player'", "Binario SUID propiedad de root"],
        objetivo_tecnico="Localizar el binario con bit SUID y usarlo para leer /root/flag.txt.",
        objetivo_investigacion="Demostrar que un SUID innecesario permite a un usuario sin privilegios leer secretos de root.",
        hint1="Conecta por SSH y busca archivos con permiso SUID: find / -perm -4000 -type f 2>/dev/null",
        hint2="El binario sospechoso (por ejemplo /usr/local/bin/readflag) lee /root/flag.txt cuando se ejecuta.",
        hint3="Ejecuta el binario SUID directamente: /usr/local/bin/readflag y captura la salida RP{...}.",
        spec=dict(user="player", password="player", bin="readflag"),
    ),
    dict(
        slug="el-backup-de-medianoche", title="El Backup de Medianoche",
        category="Linux", difficulty=2,
        template="linux_cron",
        cert="Fundamentos de Pentesting (eJPT)", domain="Explotacion de Sistemas Linux",
        series="casos-rd", region="Nacional",
        rd="RD-035", provincia="Santo Domingo",
        ubicacion="Servidor de respaldos de un taller de imprenta en la zona industrial",
        fecha="2026-09-05", incidente="Cron de root ejecutando un script modificable por un usuario sin privilegios",
        resumen="Un taller de imprenta programa un respaldo nocturno vía cron con permisos de root. El script que ejecuta el cron es modificable por cualquier usuario. Hay que inyectar una orden que permita leer la bandera cuando corra el cron.",
        evidencias=["Acceso SSH con usuario 'player'", "Entrada en /etc/cron.d que ejecuta un script con permisos amplios"],
        objetivo_tecnico="Detectar un trabajo de cron que corre como root y que usa un script escribible, y abusar de él.",
        objetivo_investigacion="Obtener la bandera que el cron deja o revela tras ejecutar el script manipulado.",
        hint1="Revisa /etc/cron.d y los scripts que invoca; comprueba permisos con ls -l.",
        hint2="El script /usr/local/bin/backup.sh es escribible por el grupo o por todos (chmod o+w).",
        hint3="Añade una línea al script que copie /root/flag.txt a /tmp/ o lo imprima, y espera a que el cron lo ejecute.",
        spec=dict(user="player", password="player"),
    ),
    dict(
        slug="el-admin-de-la-residencia", title="El Admin de la Residencia",
        category="Linux", difficulty=3,
        template="linux_sudo",
        cert="Pentesting Intermedio (PNPT)", domain="Post-explotacion Linux",
        series="casos-rd", region="Cibao",
        rd="RD-036", provincia="Santiago",
        ubicacion="Servidor de la residencia estudiantil 'Residencia del Yaque'",
        fecha="2026-09-11", incidente="Configuración sudo insegura que permite escalada por variable de entorno",
        resumen="La residencia estudiantil administra un servidor donde el usuario 'player' puede ejecutar un comando con sudo, pero la configuración conserva variables de entorno peligrosas (env_keep de PATH u otras). Hay que explotar esa debilidad para escalar a root.",
        evidencias=["Acceso SSH con usuario 'player'", "Salida de 'sudo -l' que revela una regla explotable"],
        objetivo_tecnico="Aprovechar una regla de sudo con env_keep para secuestrar la ejecución y leer la bandera.",
        objetivo_investigacion="Demostrar cómo una configuración sudo laxa permite la escalada de privilegios.",
        hint1="Ejecuta sudo -l para ver qué comandos puede correr 'player' sin contraseña.",
        hint2="La regla conserva PATH (env_keep+=PATH): puedes apuntar a un binario controlado por ti.",
        hint3="Crea un binario malicioso con el mismo nombre del comando permitido en un directorio que tú controles y ejecútalo vía sudo.",
        spec=dict(user="player", password="player"),
    ),

    # ============================ CRYPTO ===========================
    dict(
        slug="el-mensaje-del-concho", title="El Mensaje del Concho",
        category="Crypto", difficulty=1,
        template="crypto_base64",
        cert="Seguridad General (Security+)", domain="Criptografia",
        series="casos-rd", region="Gran Santo Domingo",
        rd="RD-037", provincia="Distrito Nacional",
        ubicacion="Mensaje interceptado en un grupo de choferes de carro público",
        fecha="2026-09-13", incidente="Mensaje codificado en varias capas de Base64",
        resumen="Un mensaje incautado a un grupo de choferes está codificado en Base64 varias veces. El contenido, al decodificarse en cascada, revela un dato clave para la investigación.",
        evidencias=["Archivo de texto con el mensaje codificado"],
        objetivo_tecnico="Decodificar repetidamente el contenido en Base64 hasta obtener texto legible.",
        objetivo_investigacion="Recuperar la bandera escondida tras varias capas de codificación.",
        hint1="El archivo parece texto aleatorio: es Base64. Decodifícalo una vez.",
        hint2="La salida de la primera decodificación también es Base64. Repite el proceso.",
        hint3="Son tres capas de Base64. Tras la tercera obtienes la bandera RP{...}.",
        spec=dict(layers=3),
    ),
    dict(
        slug="la-carta-de-la-duarte", title="La Carta de la Duarte",
        category="Crypto", difficulty=2,
        template="crypto_vigenere",
        cert="Seguridad General (Security+)", domain="Criptografia",
        series="casos-rd", region="Cibao",
        rd="RD-038", provincia="Santiago",
        ubicacion="Carta cifrada hallada en una pensión de la Av. Duarte, Santiago",
        fecha="2026-09-16", incidente="Documento cifrado con el cifrado de Vigenère",
        resumen="Una carta escrita a mano, cifrada con el método de Vigenère, fue hallada en una pensión. La clave es una palabra relacionada con la plataforma. Descifrarla revela la bandera.",
        evidencias=["Archivo con el texto cifrado y una nota sobre la clave"],
        objetivo_tecnico="Descifrar un texto Vigenère conocida la clave (o deduciéndola del contexto).",
        objetivo_investigacion="Recuperar el mensaje original y la bandera oculta.",
        hint1="El cifrado es Vigenère. La nota dice que la clave es el nombre de la plataforma en minúsculas.",
        hint2="La clave es 'rootpath'. Cada letra desplaza la del texto según la letra de la clave.",
        hint3="Implementa o usa una herramienta de descifrado Vigenère con clave 'rootpath' sobre el texto.",
        spec=dict(key="rootpath"),
    ),
    dict(
        slug="el-chat-del-parque-mirador", title="El Chat del Parque Mirador",
        category="Crypto", difficulty=3,
        template="crypto_rsa",
        cert="Fundamentos de Pentesting (eJPT)", domain="Criptografia y Forense",
        series="casos-rd", region="Gran Santo Domingo",
        rd="RD-039", provincia="Distrito Nacional",
        ubicacion="Mensaje cifrado con RSA de clave débil interceptado en un chat",
        fecha="2026-09-20", incidente="RSA con módulo pequeño factorizable",
        resumen="Un chat cifrado usaba RSA, pero generó la clave con primos demasiado pequeños. Se capturaron el módulo (n), el exponente (e) y el mensaje cifrado (c). Factorizar n permite descifrar el mensaje y obtener la bandera.",
        evidencias=["Archivo con n, e y c", "Clave pública RSA de módulo pequeño"],
        objetivo_tecnico="Factorizar el módulo n y calcular el exponente privado d para descifrar c.",
        objetivo_investigacion="Recuperar el texto plano del mensaje cifrado (la bandera).",
        hint1="n es pequeño: se puede factorizar. Usa el método de Pollard rho o Fermat.",
        hint2="Con los factores p y q calcula φ(n) = (p-1)(q-1) y luego d = inverso de e módulo φ(n).",
        hint3="Descifra con m = pow(c, d, n) y convierte el número a bytes para ver la bandera.",
        spec=dict(bits=28),
    ),

    # ========================== FORENSICS =========================
    dict(
        slug="el-pendrive-del-parqueo", title="El Pendrive del Parqueo",
        category="Forensics", difficulty=1,
        template="forensics_strings",
        cert="Seguridad General (Security+)", domain="Forense",
        series="casos-rd", region="Este",
        rd="RD-040", provincia="La Romana",
        ubicacion="USB hallado en el parqueo del campus UCE",
        fecha="2026-09-22", incidente="Dispositivo USB con archivo binario que contiene texto oculto",
        resumen="Un USB perdido en el parqueo contiene un volcado binario. Entre los datos hay una cadena de texto (la bandera) embebida que no es visible abriendo el archivo con un editor común.",
        evidencias=["Archivo binario evidencia.bin"],
        objetivo_tecnico="Extraer cadenas de texto legibles de un archivo binario.",
        objetivo_investigacion="Localizar la bandera RP{...} incrustada en el volcado.",
        hint1="Un archivo binario puede contener texto. Busca cadenas ASCII legibles.",
        hint2="Usa la técnica 'strings' (o un script que busque secuencias imprimibles).",
        hint3="Busca el patrón RP{...} entre las cadenas extraídas.",
        spec=dict(),
    ),
    dict(
        slug="la-foto-del-malecon", title="La Foto del Malecón",
        category="Forensics", difficulty=2,
        template="forensics_meta",
        cert="Seguridad General (Security+)", domain="Forense",
        series="casos-rd", region="Gran Santo Domingo",
        rd="RD-041", provincia="Distrito Nacional",
        ubicacion="Imagen digital hallada en un teléfono recuperado en el Malecón",
        fecha="2026-09-25", incidente="Información oculta en los metadatos de una imagen PNG",
        resumen="Una foto tomada en el Malecón tiene información oculta en sus metadatos (chunks de la imagen). El investigador debe inspeccionar los bloques del archivo PNG para hallar el dato confidencial.",
        evidencias=["Imagen foto.png"],
        objetivo_tecnico="Inspeccionar los chunks (bloques) de un PNG, en particular los de texto (tEXt).",
        objetivo_investigacion="Recuperar la bandera oculta en los metadatos de la imagen.",
        hint1="Un PNG está formado por chunks: IHDR, IDAT, tEXt, IEND. Inspecciónalos.",
        hint2="El chunk tEXt almacena texto en claro (clave\0valor). Búscalo.",
        hint3="Lee el valor del chunk tEXt para encontrar la bandera RP{...}.",
        spec=dict(),
    ),
    dict(
        slug="la-captura-de-la-autopista", title="La Captura de la Autopista",
        category="Forensics", difficulty=3,
        template="forensics_pcap",
        cert="Fundamentos de Pentesting (eJPT)", domain="Criptografia y Forense",
        series="casos-rd", region="Nacional",
        rd="RD-042", provincia="Santo Domingo",
        ubicacion="Captura de tráfico de red en un punto de la Autopista Duarte",
        fecha="2026-09-28", incidente="Exfiltración de datos capturada en un volcado de red (pcap)",
        resumen="Un sensor capturó tráfico de red donde un atacante exfiltró información. Dentro del volcado hay una petición HTTP con la bandera codificada en Base64. Hay que analizar el pcap y decodificar el dato.",
        evidencias=["Archivo de captura trafico.pcap"],
        objetivo_tecnico="Analizar un pcap y localizar una petición HTTP con un parámetro en Base64.",
        objetivo_investigacion="Decodificar el valor en Base64 para recuperar la bandera.",
        hint1="El pcap contiene una petición GET con un parámetro que parece Base64.",
        hint2="Busca en los datos del paquete un valor largo en Base64 (data=...).",
        hint3="Decodifica el valor Base64 para obtener la bandera RP{...}.",
        spec=dict(),
    ),

    # ============================= AD =============================
    dict(
        slug="el-directorio-de-la-alcaldia", title="El Directorio de la Alcaldía",
        category="AD", difficulty=1,
        template="ad_ldap",
        cert="Pentesting de Active Directory (PNPT)", domain="Enumeracion de Active Directory",
        series="casos-rd", region="Este",
        rd="RD-043", provincia="La Altagracia",
        ubicacion="Volcado LDAP de un directorio corporativo municipal (entidad ficticia)",
        fecha="2026-09-30", incidente="Enumeración LDAP anónima que expone atributos codificados",
        resumen="Un enlace LDAP anónimo permitió volcar el directorio de una alcaldía ficticia. Entre los atributos hay una descripción codificada en Base64 que contiene la bandera.",
        evidencias=["Archivo de volcado ldap_dump.ldif"],
        objetivo_tecnico="Analizar un volcado LDIF y decodificar atributos description en Base64.",
        objetivo_investigacion="Recuperar la bandera oculta en un atributo codificado.",
        hint1="En LDIF, los atributos binarios se marcan con doble dos puntos (::) y van en Base64.",
        hint2="Busca líneas 'description:: ...' en el volcado.",
        hint3="Decodifica el Base64 de la descripción de la cuenta de servicio (svc_backup).",
        spec=dict(),
    ),
    dict(
        slug="la-ruta-al-dominio", title="La Ruta al Dominio",
        category="AD", difficulty=2,
        template="ad_bloodhound",
        cert="Pentesting de Active Directory (PNPT)", domain="Enumeracion de Active Directory",
        series="casos-rd", region="Nacional",
        rd="RD-044", provincia="Santo Domingo",
        ubicacion="Export de BloodHound de un dominio corporativo (entidad ficticia)",
        fecha="2026-10-02", incidente="Ruta de ataque a Domain Admins visible en el grafo de BloodHound",
        resumen="Un export de BloodHound (grafo JSON) revela una ruta desde un usuario comprometido hasta el control del dominio. La bandera está en la descripción (Base64) del usuario clave de esa ruta.",
        evidencias=["Archivo bloodhound.json con nodos y edges"],
        objetivo_tecnico="Recorrer el grafo buscando relaciones AdminTo hacia Domain Controllers.",
        objetivo_investigacion="Identificar al usuario con AdminTo y decodificar su descripción (la bandera).",
        hint1="BloodHound representa relaciones como edges: busca edges con label 'AdminTo'.",
        hint2="El edge relevante apunta a un nodo con 'DOMAIN CONTROLLERS'.",
        hint3="La descripción (Base64) del usuario origen de ese edge es la bandera.",
        spec=dict(),
    ),
    dict(
        slug="el-ticket-de-la-noche", title="El Ticket de la Noche",
        category="AD", difficulty=3,
        template="ad_kerberoast",
        cert="Pentesting de Active Directory (PNPT)", domain="Ataques a credenciales",
        series="casos-rd", region="Cibao",
        rd="RD-045", provincia="Santiago",
        ubicacion="Hash TGS-REP (Kerberoasting) de una cuenta de servicio",
        fecha="2026-10-05", incidente="Ataque de Kerberoasting: hash RC4 de una cuenta de servicio crackeable",
        resumen="Un atacante obtuvo un hash TGS-REP ($krb5tgs$23$) de la cuenta de servicio svc_backup. La contraseña es débil y aparece en un diccionario pequeño. Crackearla revela la bandera RP{usuario_contraseña}.",
        evidencias=["Archivo kerberoast.txt con el hash"],
        objetivo_tecnico="Crackear un hash Kerberoast (RC4-HMAC / etype 23) contra una wordlist pequeña.",
        objetivo_investigacion="Recuperar la contraseña de la cuenta de servicio y formar la bandera.",
        hint1="Es un hash $krb5tgs$23$ (Kerberoasting). El checksum es HMAC-MD5 de la clave NTLM.",
        hint2="La clave es el hash NTLM (MD4 UTF-16LE) de la contraseña.",
        hint3="Prueba contraseñas de una wordlist de servicios (p.ej. 'Summer2023!') y forma RP{svc_backup_<contraseña>}.",
        spec=dict(password="Summer2023!", user="svc_backup", realm="ROOTPATH.LOCAL", spn="MSSQLSvc/db01.rootpath.local:1433"),
    ),

    # ============================= BLUE ===========================
    dict(
        slug="la-fuga-del-portal", title="La Fuga del Portal",
        category="Blue", difficulty=1,
        template="blue_weblog",
        cert="Blue Team (BTL1)", domain="Analisis de logs",
        series="casos-rd", region="Gran Santo Domingo",
        rd="RD-046", provincia="Distrito Nacional",
        ubicacion="Log de acceso Apache de un portal de noticias",
        fecha="2026-10-08", incidente="Exfiltración de datos vía un parámetro de una petición web",
        resumen="El log de acceso del servidor web de un portal de noticias registra una petición POST sospechosa con un parámetro codificado en Base64. Hay que analizar el log y decodificar el dato exfiltrado.",
        evidencias=["Archivo access.log"],
        objetivo_tecnico="Identificar una petición anómala en un log web y decodificar un parámetro Base64.",
        objetivo_investigacion="Recuperar la bandera contenida en el dato exfiltrado.",
        hint1="Busca peticiones POST a rutas poco comunes (p.ej. /api/export).",
        hint2="El parámetro 'data' de esa petición está en Base64.",
        hint3="Decodifica el valor de 'data' para obtener la bandera RP{...}.",
        spec=dict(),
    ),
    dict(
        slug="el-ataque-de-fuerza-bruta", title="El Ataque de Fuerza Bruta",
        category="Blue", difficulty=2,
        template="blue_authlog",
        cert="Blue Team (BTL1)", domain="Analisis de logs",
        series="casos-rd", region="Nacional",
        rd="RD-047", provincia="Santo Domingo",
        ubicacion="auth.log de un servidor Linux comprometido",
        fecha="2026-10-11", incidente="Fuerza bruta SSH seguida de acceso y persistencia",
        resumen="El auth.log muestra un ataque de fuerza bruta desde una IP, seguido de un acceso exitoso. Tras el acceso, el atacante ejecutó un comando con sudo que dejó datos codificados. Hay que reconstruir el ataque y recuperar la bandera.",
        evidencias=["Archivo auth.log"],
        objetivo_tecnico="Correlacionar eventos en auth.log y decodificar el comando del atacante.",
        objetivo_investigacion="Recuperar la bandera oculta en el comando ejecutado tras el acceso.",
        hint1="Identifica los intentos fallidos y el acceso exitoso (Accepted password).",
        hint2="Busca las líneas de sudo tras el acceso: el comando incluye un valor Base64.",
        hint3="Decodifica el valor tras 'echo ... >' en la línea sudo para obtener la bandera.",
        spec=dict(),
    ),
    dict(
        slug="el-susurro-del-dns", title="El Susurro del DNS",
        category="Blue", difficulty=3,
        template="blue_dns",
        cert="Blue Team (BTL1)", domain="Forense de red",
        series="casos-rd", region="Cibao",
        rd="RD-048", provincia="La Vega",
        ubicacion="Log DNS (formato Zeek) con exfiltración por subdominios",
        fecha="2026-10-14", incidente="Exfiltración de datos troceada en consultas DNS",
        resumen="Un log DNS muestra consultas a subdominios sospechosos (exfil.rootpath.local) que llevan datos troceados y codificados en Base32. Hay que reensamblar los fragmentos y decodificarlos.",
        evidencias=["Archivo dns.log"],
        objetivo_tecnico="Reensamblar labels de subdominios y decodificar Base32.",
        objetivo_investigacion="Recuperar la bandera exfiltrada vía DNS.",
        hint1="Cada consulta lleva un trozo de datos en el subdominio antes de .exfil.rootpath.local.",
        hint2="Los trozos están en Base32 (alfabeto A-Z2-7).",
        hint3="Une los labels en orden, añade el padding y decodifica Base32 para obtener la bandera.",
        spec=dict(),
    ),
]
